// Replace with your actual Gemini API Key from environment variables
// For local development, you might set it in your .env file
export const GEMINI_API_KEY: string = process.env.API_KEY || 'YOUR_GEMINI_API_KEY';

export const REWARD_PER_VIDEO: number = 0.10; // Value in virtual currency
export const MIN_WATCH_TIME_SECONDS: number = 30; // Minimum time in seconds to watch a video for rewards

export const YOUTUBE_API_KEY: string = 'YOUR_YOUTUBE_API_KEY'; // Placeholder
export const VIMEO_API_KEY: string = 'YOUR_VIMEO_API_KEY'; // Placeholder

export const MOCK_USERS = [
  {
    id: 'user_123',
    name: 'Alice Smith',
    email: 'alice@example.com',
    balance: 15.50,
    isActive: true,
    isAdmin: false,
    preferences: ['comedy', 'tutorials'],
    password: 'password123'
  },
  {
    id: 'user_456',
    name: 'Bob Johnson',
    email: 'bob@example.com',
    balance: 7.25,
    isActive: true,
    isAdmin: false,
    preferences: ['gaming', 'music'],
    password: 'password123'
  },
  {
    id: 'admin_789',
    name: 'Admin User',
    email: 'ad@cashviral.com', // Updated admin email
    balance: 0.00,
    isActive: true,
    isAdmin: true,
    preferences: [],
    password: 'a12' // Updated admin password
  },
];

export const MOCK_VIDEOS = [
  {
    id: 'v_youtube_intro',
    title: 'Introdução ao CASHVIRAL',
    thumbnail: 'https://picsum.photos/320/180?random=intro',
    duration: 180, // seconds
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=intro_cashviral', // Placeholder
    views: 500,
    averageWatchTime: 120,
    likes: 25,
    isActive: true,
  },
  {
    id: 'v_youtube_cat_funny',
    title: 'Gato Engraçado Falando',
    thumbnail: 'https://picsum.photos/320/180?random=cat_funny',
    duration: 90,
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=cat_funny_viral',
    views: 120000,
    averageWatchTime: 80,
    likes: 5000,
    isActive: true,
    category: 'humor',
  },
  {
    id: 'v_youtube_dog_trick',
    title: 'Cachorro Faz Truques Incríveis',
    thumbnail: 'https://picsum.photos/320/180?random=dog_trick',
    duration: 150,
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=dog_trick_viral',
    views: 85000,
    averageWatchTime: 130,
    likes: 3200,
    isActive: true,
    category: 'animais',
  },
  {
    id: 'v_youtube_fail_compilation',
    title: 'Melhores Falhas Épicas 2024',
    thumbnail: 'https://picsum.photos/320/180?random=fail_compilation',
    duration: 300,
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=fail_compilation',
    views: 250000,
    averageWatchTime: 200,
    likes: 15000,
    isActive: true,
    category: 'humor',
  },
  {
    id: 'v_youtube_baby_laugh',
    title: 'Bebê Rindo Descontroladamente',
    thumbnail: 'https://picsum.photos/320/180?random=baby_laugh',
    duration: 60,
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=baby_laugh_viral',
    views: 180000,
    averageWatchTime: 50,
    likes: 7000,
    isActive: true,
    category: 'fofo',
  },
  {
    id: 'v_youtube_challenge_dance',
    title: 'Desafio de Dança Viral do TikTok',
    thumbnail: 'https://picsum.photos/320/180?random=dance_challenge',
    duration: 120,
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=dance_challenge',
    views: 300000,
    averageWatchTime: 90,
    likes: 20000,
    isActive: true,
    category: 'desafio',
  },
  {
    id: 'v_youtube_prank_public',
    title: 'Pegadinha Hilária em Público',
    thumbnail: 'https://picsum.photos/320/180?random=prank_public',
    duration: 200,
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=prank_public',
    views: 100000,
    averageWatchTime: 150,
    likes: 6000,
    isActive: true,
    category: 'pegadinha',
  },
  {
    id: 'v_youtube_animal_rescue',
    title: 'Resgate Emocionante de Animais',
    thumbnail: 'https://picsum.photos/320/180?random=animal_rescue',
    duration: 280,
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=animal_rescue',
    views: 75000,
    averageWatchTime: 200,
    likes: 4000,
    isActive: true,
    category: 'emocionante',
  },
  {
    id: 'v_youtube_cooking_fail',
    title: 'Receitas que Deram Errado',
    thumbnail: 'https://picsum.photos/320/180?random=cooking_fail',
    duration: 180,
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=cooking_fail',
    views: 90000,
    averageWatchTime: 140,
    likes: 4500,
    isActive: true,
    category: 'humor',
  },
  {
    id: 'v_youtube_talent_show',
    title: 'Apresentação de Talentos Surpreendente',
    thumbnail: 'https://picsum.photos/320/180?random=talent_show',
    duration: 220,
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=talent_show',
    views: 150000,
    averageWatchTime: 180,
    likes: 8000,
    isActive: true,
    category: 'talento',
  },
  {
    id: 'v_youtube_life_hacks',
    title: 'Truques Geniais para o Dia a Dia',
    thumbnail: 'https://picsum.photos/320/180?random=life_hacks',
    duration: 360,
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=life_hacks',
    views: 200000,
    averageWatchTime: 250,
    likes: 10000,
    isActive: true,
    category: 'dicas',
  },
  {
    id: 'v_youtube_funny_kids',
    title: 'Crianças Fazendo Coisas Hilárias',
    thumbnail: 'https://picsum.photos/320/180?random=funny_kids',
    duration: 100,
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=funny_kids',
    views: 130000,
    averageWatchTime: 70,
    likes: 6000,
    isActive: true,
    category: 'fofo',
  },
  {
    id: 'v_youtube_epic_fails_sports',
    title: 'Falhas de Esportes Mais Engraçadas',
    thumbnail: 'https://picsum.photos/320/180?random=epic_fails_sports',
    duration: 280,
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=epic_fails_sports',
    views: 160000,
    averageWatchTime: 210,
    likes: 9000,
    isActive: true,
    category: 'esportes',
  },
  {
    id: 'v_youtube_satisfying_video',
    title: 'Vídeos Satisfatórios para Relaxar',
    thumbnail: 'https://picsum.photos/320/180?random=satisfying',
    duration: 400,
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=satisfying_video',
    views: 110000,
    averageWatchTime: 300,
    likes: 7500,
    isActive: true,
    category: 'relaxamento',
  },
  {
    id: 'v_youtube_magic_trick',
    title: 'Truques de Mágica Simples de Fazer',
    thumbnail: 'https://picsum.photos/320/180?random=magic_trick',
    duration: 170,
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=magic_trick',
    views: 80000,
    averageWatchTime: 130,
    likes: 4000,
    isActive: true,
    category: 'entretenimento',
  },
  {
    id: 'v_youtube_reaction_compilation',
    title: 'Melhores Reações da Internet',
    thumbnail: 'https://picsum.photos/320/180?random=reaction_compilation',
    duration: 210,
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=reaction_compilation',
    views: 190000,
    averageWatchTime: 160,
    likes: 11000,
    isActive: true,
    category: 'humor',
  },
  {
    id: 'v_youtube_travel_vlog',
    title: 'Melhores Lugares para Viajar em 2024',
    thumbnail: 'https://picsum.photos/320/180?random=travel_vlog',
    duration: 450,
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=travel_vlog',
    views: 95000,
    averageWatchTime: 350,
    likes: 5000,
    isActive: true,
    category: 'viagem',
  },
  {
    id: 'v_youtube_gaming_epic_moments',
    title: 'Momentos Épicos de Jogos',
    thumbnail: 'https://picsum.photos/320/180?random=gaming_epic_moments',
    duration: 320,
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=gaming_epic_moments',
    views: 140000,
    averageWatchTime: 280,
    likes: 8000,
    isActive: true,
    category: 'jogos',
  },
  {
    id: 'v_youtube_science_experiment',
    title: 'Experimentos Científicos Incríveis',
    thumbnail: 'https://picsum.photos/320/180?random=science_experiment',
    duration: 260,
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=science_experiment',
    views: 70000,
    averageWatchTime: 200,
    likes: 3000,
    isActive: true,
    category: 'ciência',
  },
  {
    id: 'v_youtube_music_viral',
    title: 'Músicas Virais do Momento',
    thumbnail: 'https://picsum.photos/320/180?random=music_viral',
    duration: 200,
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=music_viral',
    views: 220000,
    averageWatchTime: 150,
    likes: 12000,
    isActive: true,
    category: 'música',
  },
  {
    id: 'v_youtube_workout_motivation',
    title: 'Motivação para Treinar Pesado',
    thumbnail: 'https://picsum.photos/320/180?random=workout_motivation',
    duration: 300,
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=workout_motivation',
    views: 60000,
    averageWatchTime: 250,
    likes: 3500,
    isActive: true,
    category: 'fitness',
  },
];

export const MOCK_ADMIN_DASHBOARD_DATA = {
  totalUsers: 1500,
  totalVideosWatched: 250000,
  totalPendingPayout: 1250.75,
  dailyGrowth: [
    { date: 'Seg', users: 10, videos: 500 },
    { date: 'Ter', users: 15, videos: 750 },
    { date: 'Qua', users: 12, videos: 600 },
    { date: 'Qui', users: 20, videos: 1000 },
    { date: 'Sex', users: 18, videos: 900 },
    { date: 'Sáb', users: 25, videos: 1200 },
    { date: 'Dom', users: 30, videos: 1500 },
  ],
  weeklyGrowth: [
    { week: 'Sem 1', users: 100, videos: 5000 },
    { week: 'Sem 2', users: 120, videos: 6000 },
    { week: 'Sem 3', users: 150, videos: 7500 },
    { week: 'Sem 4', users: 180, videos: 9000 },
  ],
  monthlyGrowth: [
    { month: 'Jan', users: 300, videos: 15000 },
    { month: 'Fev', users: 350, videos: 17500 },
    { month: 'Mar', users: 400, videos: 20000 },
  ],
  activeUsers: 850,
};

export const MOCK_WITHDRAWAL_REQUESTS = [
  {
    id: 'w_1',
    userId: 'user_123',
    userName: 'Alice Smith',
    amount: 10.00,
    method: 'PIX',
    status: 'pending',
    requestDate: '2024-07-20T10:00:00Z',
  },
  {
    id: 'w_2',
    userId: 'user_456',
    userName: 'Bob Johnson',
    amount: 5.00,
    method: 'MercadoPago',
    status: 'approved',
    requestDate: '2024-07-19T15:30:00Z',
  },
];

export const MOCK_INVITE_BONUS_CONFIG = {
  bonusPerInvite: 0.50,
  minInviteeWatchTime: 600, // 10 minutes
};

// Updated AD_PLACEMENT_OPTIONS to include Portuguese labels
export const AD_PLACEMENT_OPTIONS = [
  { value: 'video-feed', label: 'Feed de Vídeos' },
  { value: 'video-player-pre-roll', label: 'Player de Vídeo (Pré-vídeo)' },
  { value: 'video-player-mid-roll', label: 'Player de Vídeo (Meio do vídeo)' },
  { value: 'video-player-post-roll', label: 'Player de Vídeo (Pós-vídeo)' },
  { value: 'user-profile-sidebar', label: 'Barra Lateral do Perfil do Usuário' },
  { value: 'rewards-page-banner', label: 'Banner da Página de Recompensas' },
  { value: 'footer', label: 'Rodapé' },
  { value: 'header', label: 'Cabeçalho' },
  { value: 'global-pop-up', label: 'Pop-up Global' },
];

export const ADSENSE_MOCK_DATA = {
  adsenseId: 'ca-pub-8115686562988147', // Updated to match the AdSense client ID
  verificationCodes: ['<meta name="google-adsense-account" content="ca-pub-8115686562988147">'], // Example using the correct pub-ID
  adBlocks: [], // Revertido para array vazio
  revenueReports: [
    { date: '2024-07-01', revenue: 12.34, clicks: 120, impressions: 5000 },
    { date: '2024-07-02', revenue: 15.67, clicks: 150, impressions: 6000 },
    { date: '2024-07-03', revenue: 10.00, clicks: 90, impressions: 4500 },
  ],
};

export const MOCK_APP_SETTINGS = {
  appName: 'CASHVIRAL',
  appLogoUrl: 'https://picsum.photos/50/50?random=logo',
  privacyPolicyUrl: '#',
  termsOfServiceUrl: '#',
  youtubeApiKey: YOUTUBE_API_KEY,
  vimeoApiKey: VIMEO_API_KEY,
  geminiApiKey: GEMINI_API_KEY,
  vimeoUserId: '250829792', // Added for Vimeo sync
};